---
- name: deploy cert-manager and LetsEncrypt issuers to workload cluster
  hosts: mgmtcp0

  environment:
    CLUSTER_NAME: "{{ CLUSTER_NAME }}"
    CERTM_VERSION: "{{ CERTM_VERSION }}"

  tasks:
    - name: add Jetstack / Cert-Manager Helm repo on mgmtcp0
      kubernetes.core.helm_repository:
        name: jetstack 
        repo_url: "https://charts.jetstack.io"

    - name: install cert-manager to workload cluster
      ansible.builtin.shell:
        cmd: "KUBECONFIG=./{{ CLUSTER_NAME }}.kubeconfig helm upgrade --install cert-manager jetstack/cert-manager \
              --version {{ CERTM_VERSION }} \
              --namespace cert-manager \
              --create-namespace \
              --set crds.enabled=true"

